# UNIDAD 1 - 02 Manipulación de datos con Python

## 1. Básicos de Python

Quienes no están familiarizadxs, sugerimos que busquen algún tutorial. Si bien recorreremos lo básico, nunca está de más aprender un poco.

No vamos a explicar mucho las celdas, se van a ir comprendiendo por si solas, pero sí es necesario leer con detalle la sintaxis y analizar la salida del código.

In [1]:
print("Hola mundo")

Hola mundo


In [2]:
nombre = input("Ingresa tu nombre: ")
print("Bienvenidx ", nombre )

Ingresa tu nombre: tita ichu
Bienvenidx  tita ichu


In [3]:
x = 1
print(x)

1


In [4]:
nombre = "Jorgelina"
print(nombre)

Jorgelina


In [9]:
4/2

2.0

In [10]:
4//2

2

In [11]:
9%2

1

In [12]:
x = True
print(x)
print(not x)

True
False


In [13]:
if 5 == 6:
    print(1)
elif 6 == 6:
    print(2)
else:
    print(3)

2


In [14]:
for i in range(0,21,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [16]:
for i in range(0,22,2):
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [15]:
for i in range(0,21):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [17]:
for i in range(0,21,5):
    print(i)

0
5
10
15
20


In [18]:
i = 1
while i <= 10:
    print(i)
    i = i + 1

1
2
3
4
5
6
7
8
9
10


In [19]:
print(i)

11


In [20]:
while True:
    nombre_de_usuario = input("Ingresa tu nombre de usuario: ")
    if nombre_de_usuario == "Jorgelina":
        print("Bienvenida Jorgelina")
        break
    else:
        print("Nombre de usuario incorrecto")




Ingresa tu nombre de usuario: tita ichu
Nombre de usuario incorrecto
Ingresa tu nombre de usuario: Jorgelina
Bienvenida Jorgelina


In [21]:
lista_de_flores = ["Rosa", "Lila", "Azucena"]

In [22]:
primer_elemento = lista_de_flores[0]
print(primer_elemento)

Rosa


In [23]:
ultimos_dos_elementos = lista_de_flores[1:3]
print(ultimos_dos_elementos)

['Lila', 'Azucena']


In [24]:
for i in lista_de_flores:
    print(i)

Rosa
Lila
Azucena


In [25]:
for i in lista_de_flores[1:3]:
    print(i)

Lila
Azucena


In [26]:
diccionario_de_notas = {'Inglés':'10', 'Matematica':'8', 'Historia':'6'}
print(diccionario_de_notas)

{'Inglés': '10', 'Matematica': '8', 'Historia': '6'}


In [27]:
print(diccionario_de_notas.keys())

dict_keys(['Inglés', 'Matematica', 'Historia'])


In [28]:
print(diccionario_de_notas.values())

dict_values(['10', '8', '6'])


In [29]:
datos = {"Nombre":"Jorgelina", "Edad":30, "País":"Argentina"}

In [30]:
nombre = datos["Nombre"]
edad = datos["Edad"]
pais = datos["País"]
print(nombre)
print(edad)
print(pais)


Jorgelina
30
Argentina


In [31]:
type(nombre), type(edad)

(str, int)

In [32]:
for key in datos:
        print(datos[key])

Jorgelina
30
Argentina


In [33]:
tupla_de_flores = ("Rosa","Lila","Azucena")

In [34]:
tupla_de_flores[0:2]

('Rosa', 'Lila')

In [35]:
tupla_de_flores[0:3]

('Rosa', 'Lila', 'Azucena')

In [36]:
tupla_de_flores[1:2]

('Lila',)

In [37]:
tupla_de_flores[1:3]

('Lila', 'Azucena')

In [38]:
for item in tupla_de_flores:
    print(item)

Rosa
Lila
Azucena


In [39]:
x = ["red",1,True]

In [ ]:
x[1]

1

In [41]:
x.append( "14" )
print(x)

['red', 1, True, '14']


In [42]:
def Suma(x,y):
    sum = x + y
    return sum

In [43]:
resultado = Suma(5,7)
print(resultado)

12


In [44]:
def Incrementar_uno(x,y):
    x = x + 1
    y = y + 1
    return x,y

In [45]:
num1, num2 = Incrementar_uno(5,7)
print(num1)
print(num2)

6
8


## 2. Liberías Numpy y Pandas

Cargamos las liberías más utilizadas:

- Pandas: para trabajar con tablas de datos.
- Numpy: para realizar cálculos y funciones matemáticas.
- Matplotlib: para graficar.
- Seaborn: para visualizar datos.

Veremos lo escencial de numpy y pandas, dejamos matplotlib y seaborn para cuando aparezcan.

Nuevamente, no daremos muchas explicaciones, se sugiere correr las celdas a conciencia. Hay miles de tutoriales y cheatsheets en la web para complementar.


In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### 2.1 Numpy

El tipo de dato básico de numpy es el array. Un array se puede pensar como una *multimatriz* en el sentido de que, a partir de escalares, vectores, matrices, 1-formas, se van construyendo, anidando estas estructuras. En matemática los podemos pensar como *tensores*, un tensor es un objeto algebraico que es independiente del sistema de coordenadas. Así es como a las aplicaciones (además del interés matemático en sí) a áreas como la físicas se le agregan aplicaciones a la ciencia de la computación, y dentro de éstas, y bastante recientemente, al desarrollo de redes neuronales (entre otras!).

En numpy podemos trabajar con matrices como arrays 2D. Veremos cómo las matrices no son listas de enteros, sino que tienen su propia estructura algebraica (dada por la clase array de numpy).

In [47]:
array1D = np.array([1,2,3,4,5])
print(array1D)

[1 2 3 4 5]


In [48]:
print(array1D.ndim)

1


In [50]:
array2D = np.array([[1,2,3], [4,5,6]])
print(array2D)

[[1 2 3]
 [4 5 6]]


In [51]:
print(array2D.ndim)

2


In [52]:
array3D = np.array([[[1,2,3],[-1,-2,-3]],[[4,5,6],[-4,-5,-6]]])
print(array3D)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [53]:
print(array3D.ndim)

3


In [54]:
print(array2D[1])

[4 5 6]


In [55]:
print(array2D[0])

[1 2 3]


In [56]:
print(array2D[1][0])

4


In [57]:
print(array2D[1,0])

4


In [58]:
print(array3D[1,0,0])

4


In [59]:
print(array3D[0,1,0])

-1


In [60]:
 print(array3D[0])

[[ 1  2  3]
 [-1 -2 -3]]


In [61]:
print(array3D[0,1])

[-1 -2 -3]


In [62]:
print(array1D)
print(array1D.shape)

[1 2 3 4 5]
(5,)


In [63]:
print(array2D)
print(array2D.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [64]:
print(array3D)
print(array3D.shape)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]
(2, 2, 3)


In [65]:
for i in array1D:
    print(i)

1
2
3
4
5


In [66]:
for i in array2D:
    for j in i:
        print(j)

1
2
3
4
5
6


In [67]:
for i in array3D:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]


In [68]:
for i in array3D:
    for j in i:
        print(j)

[1 2 3]
[-1 -2 -3]
[4 5 6]
[-4 -5 -6]


In [69]:
for i in array3D:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [70]:
array_de_ceros = np.zeros(10)
print(array_de_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [72]:
array_de_ceros = array_de_ceros.astype(int)
print(array_de_ceros)

[0 0 0 0 0 0 0 0 0 0]


In [73]:
array_de_unos = np.ones(10)
print(array_de_unos)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [74]:
array_de_unos = np.ones(10).astype(int)
print(array_de_unos)

[1 1 1 1 1 1 1 1 1 1]


In [75]:
array_pre_llenado = np.full(10,5)
print(array_pre_llenado)

[5 5 5 5 5 5 5 5 5 5]


In [77]:
array_pre_llenado = np.full(10,5.)
print(array_pre_llenado)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [78]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [80]:
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [81]:
lista_de_Python = [[1,2,3],[4,5,6]]
print(lista_de_Python)

[[1, 2, 3], [4, 5, 6]]


In [82]:
type(lista_de_Python)

list

In [83]:
print(lista_de_Python + 2)

TypeError: ignored

In [84]:
print(matrix - 2)

[[-1  0  1]
 [ 2  3  4]]


In [85]:
print(lista_de_Python - 2)

TypeError: ignored

In [86]:
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [87]:
print(lista_de_Python * 2) #concatena consigo misma

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [88]:
print(matrix / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [89]:
print(lista_de_Python/2)

TypeError: ignored

In [90]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [91]:
print(matrix // 2)

[[0 1 1]
 [2 2 3]]


In [92]:
print(lista_de_Python //2)

TypeError: ignored

In [93]:
print(matrix**2)

[[ 1  4  9]
 [16 25 36]]


In [94]:
print(lista_de_Python**2)

TypeError: ignored

In [95]:
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [97]:
matrix_trasp = matrix.T

In [98]:
type(matrix), type(matrix_trasp)

(numpy.ndarray, numpy.ndarray)

In [102]:
matrix.shape, matrix_trasp.shape

((2, 3), (3, 2))

In [96]:
print(lista_de_Python.T)

AttributeError: ignored

In [103]:
matrix1 = np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrix1)

[[-1 -2 -3]
 [-4 -5 -6]]


In [104]:
print(matrix + matrix1)

[[0 0 0]
 [0 0 0]]


In [105]:
lista_de_Python1 = [[-1,-2,-3],[-4,-5,-6]]
print(lista_de_Python + lista_de_Python1)

[[1, 2, 3], [4, 5, 6], [-1, -2, -3], [-4, -5, -6]]


In [106]:
print(matrix - matrix1)

[[ 2  4  6]
 [ 8 10 12]]


In [107]:
print(lista_de_Python - lista_de_Python1)

TypeError: ignored

In [108]:
print(matrix*matrix1) #multiplica elemento a elemento

[[ -1  -4  -9]
 [-16 -25 -36]]


In [109]:
print(lista_de_Python*lista_de_Python1)

TypeError: ignored

In [110]:
print(matrix/matrix1)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [111]:
print(lista_de_Python/lista_de_Python1)

TypeError: ignored

In [112]:
print(matrix//matrix1)

[[-1 -1 -1]
 [-1 -1 -1]]


In [113]:
print(lista_de_Python//lista_de_Python1)

TypeError: ignored

In [114]:
m1 = np.array([[1,2,3],[4,5,6],[0,0,0]])
print(m1)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [116]:
m1.shape

(3, 3)

In [117]:
m2 = np.array([[-1,-2,-3],[-4,-5,-6],[0,0,0]])
print(m2)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]]


In [118]:
print(m1*m2)

[[ -1  -4  -9]
 [-16 -25 -36]
 [  0   0   0]]


In [119]:
np.matmul(m1,m2)

array([[ -9, -12, -15],
       [-24, -33, -42],
       [  0,   0,   0]])

In [120]:
np.min(matrix)

1

In [121]:
np.min(matrix1)

-6

In [122]:
np.max(matrix)

6

In [123]:
np.max(matrix1)

-1

In [124]:
np.sum(matrix)

21

In [125]:
np.sum(matrix1)

-21

In [126]:
np.mean(matrix)

3.5

In [127]:
np.mean(matrix1)

-3.5

In [128]:
np.std(matrix)

1.707825127659933

In [129]:
np.std(matrix1)

1.707825127659933

In [130]:
np.median(matrix)

3.5

In [131]:
np.median(matrix1)

-3.5

### 2.3 Pandas

El tipo de datos fundamental de pandas son los dataframes, y su versión simple llamada serie. Un dataframe no es otra cosa que una tabla de doble entrada. En dicha tabla tenemos columnas e índices, más el contenido de cada par índice-columna. Podemos tanto crear dataframes como exportarlos de archivos tipo .csv (Comma Separated Values), .xls (Excel), .json (Jason), etc.

In [132]:
mi_lista = [['Manzana','Roja'],
          ['Banana','Amarilla'],
          ['Naranja','Naranja']]

In [133]:
mi_DataFrame = pd.DataFrame(mi_lista)
mi_DataFrame

0         1
0  Manzana      Roja
1   Banana  Amarilla
2  Naranja   Naranja

In [134]:
mi_DataFrame = pd.DataFrame(mi_lista, columns=['Frutas','colores'])
mi_DataFrame

Frutas   colores
0  Manzana      Roja
1   Banana  Amarilla
2  Naranja   Naranja

In [135]:
listion = np.array([[0,1],[2,3],[4,5]])

In [136]:
listion

array([[0, 1],
       [2, 3],
       [4, 5]])

In [137]:
DataFramion = pd.DataFrame(listion, columns=['Par','Impar'])
DataFramion

Par  Impar
0    0      1
1    2      3
2    4      5

In [138]:
mi_Diccionario = {'Fruta':['Manzana','Banana','Naranja'], 'Color':['Rojo','Amarillo','Naranja']}
mi_Diccionario

{'Fruta': ['Manzana', 'Banana', 'Naranja'],
 'Color': ['Rojo', 'Amarillo', 'Naranja']}

In [139]:
DF = pd.DataFrame(mi_Diccionario)
DF

Fruta     Color
0  Manzana      Rojo
1   Banana  Amarillo
2  Naranja   Naranja

In [142]:
datinframin = pd.read_csv('cereal.csv')
datinframin

FileNotFoundError: ignored

In [141]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DataFramion.set_index('Par')

Impar
Par       
0        1
2        3
4        5

In [ ]:
datinframin.set_index('A')

KeyError: "None of ['A'] are in the columns"

In [ ]:
df = pd.read_csv('cereal.csv')
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df.set_index('Cereal Name')

Manufacturer Type  Calories  Protein (g)  Fat  \
Cereal Name                                                                  
100%_Bran                         Nabisco    C        70            4    1   
100%_Natural_Bran             Quaker Oats    C       120            3    5   
All-Bran                         Kelloggs    C        70            4    1   
All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
Almond_Delight             Ralston Purina    C       110            2    2   
...                                   ...  ...       ...          ...  ...   
Triples                     General Mills    C       110            2    1   
Trix                        General Mills    C       110            1    1   
Wheat_Chex                 Ralston Purina    C       100            3    1   
Wheaties                    General Mills    C       100            3    1   
Wheaties_Honey_Gold         General Mills    C       110            2    1   

                           Sodium  Dietary Fiber  Carbs  Sugars  \
Cereal Name                                                       
100%_Bran                     130           10.0    5.0       6   
100%_Natural_Bran              15            2.0    8.0       8   
All-Bran                      260            9.0    7.0       5   
All-Bran_with_Extra_Fiber     140           14.0    8.0       0   
Almond_Delight                200            1.0   14.0       8   
...                           ...            ...    ...     ...   
Triples                       250            0.0   21.0       3   
Trix                          140            0.0   13.0      12   
Wheat_Chex                    230            3.0   17.0       3   
Wheaties                      200            3.0   17.0       3   
Wheaties_Honey_Gold           200            1.0   16.0       8   

                           Display Shelf  Potassium  Vitamins and Minerals  \
Cereal Name                                                                  
100%_Bran                              3        280                     25   
100%_Natural_Bran                      3        135                      0   
All-Bran                               3        320                     25   
All-Bran_with_Extra_Fiber              3        330                     25   
Almond_Delight                         3         -1                     25   
...                                  ...        ...                    ...   
Triples                                3         60                     25   
Trix                                   2         25                     25   
Wheat_Chex                             1        115                     25   
Wheaties                               1        110                     25   
Wheaties_Honey_Gold                    1         60                     25   

                           Serving Size Weight  Cups per Serving  
Cereal Name                                                       
100%_Bran                                  1.0              0.33  
100%_Natural_Bran                          1.0             -1.00  
All-Bran                                   1.0              0.33  
All-Bran_with_Extra_Fiber                  1.0              0.50  
Almond_Delight                             1.0              0.75  
...                                        ...               ...  
Triples                                    1.0              0.75  
Trix                                       1.0              1.00  
Wheat_Chex                                 1.0              0.67  
Wheaties                                   1.0              1.00  
Wheaties_Honey_Gold                        1.0              0.75  

[74 rows x 14 columns]

In [ ]:
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
#df.set_index('Cereal Name', inplace=True)

In [ ]:
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df.head()

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75

In [ ]:
df.head(7)

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   
5    Apple_Cinnamon_Cheerios   General Mills    C       110            2    2   
6                Apple_Jacks        Kelloggs    C       110            2    0   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   
5     180            1.5   10.5      10              1         70   
6     125            1.0   11.0      14              2         30   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75  
5                     25                  1.0              0.75  
6                     25                  1.0              1.00

In [ ]:
df.tail()

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
69              Triples   General Mills    C       110            2    1   
70                 Trix   General Mills    C       110            1    1   
71           Wheat_Chex  Ralston Purina    C       100            3    1   
72             Wheaties   General Mills    C       100            3    1   
73  Wheaties_Honey_Gold   General Mills    C       110            2    1   

    Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
69     250            0.0   21.0       3              3         60   
70     140            0.0   13.0      12              2         25   
71     230            3.0   17.0       3              1        115   
72     200            3.0   17.0       3              1        110   
73     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75

In [ ]:
df.tail(7)

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
67    Total_Raisin_Bran   General Mills    C       140            3    1   
68    Total_Whole_Grain   General Mills    C       100            3    1   
69              Triples   General Mills    C       110            2    1   
70                 Trix   General Mills    C       110            1    1   
71           Wheat_Chex  Ralston Purina    C       100            3    1   
72             Wheaties   General Mills    C       100            3    1   
73  Wheaties_Honey_Gold   General Mills    C       110            2    1   

    Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
67     190            4.0   15.0      14              3        230   
68     200            3.0   16.0       3              3        110   
69     250            0.0   21.0       3              3         60   
70     140            0.0   13.0      12              2         25   
71     230            3.0   17.0       3              1        115   
72     200            3.0   17.0       3              1        110   
73     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
67                    100                  1.5              1.00  
68                    100                  1.0              1.00  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75

In [ ]:
df.describe()

Calories  Protein (g)        Fat      Sodium  Dietary Fiber  \
count   74.000000    74.000000  74.000000   74.000000      74.000000   
mean   105.540541     2.500000   0.945946  160.675676       2.090541   
std     18.442201     1.088546   0.963610   85.188447       2.404002   
min     50.000000     1.000000   0.000000    0.000000       0.000000   
25%    100.000000     2.000000   0.000000  131.250000       0.250000   
50%    110.000000     2.000000   1.000000  180.000000       1.500000   
75%    110.000000     3.000000   1.000000  217.500000       3.000000   
max    160.000000     6.000000   5.000000  320.000000      14.000000   

           Carbs     Sugars  Display Shelf   Potassium  Vitamins and Minerals  \
count  74.000000  74.000000      74.000000   74.000000              74.000000   
mean   14.594595   6.770270       2.175676   92.675676              28.378378   
std     4.349205   4.467684       0.833512   70.578065              22.787104   
min    -1.000000  -1.000000       1.000000   -1.000000               0.000000   
25%    12.000000   3.000000       1.000000   40.000000              25.000000   
50%    14.000000   6.000000       2.000000   90.000000              25.000000   
75%    17.000000  10.750000       3.000000  113.750000              25.000000   
max    23.000000  15.000000       3.000000  330.000000             100.000000   

       Serving Size Weight  Cups per Serving  
count            74.000000         74.000000  
mean              1.027432          0.629054  
std               0.151260          0.576843  
min               0.500000         -1.000000  
25%               1.000000          0.670000  
50%               1.000000          0.750000  
75%               1.000000          1.000000  
max               1.500000          1.500000

In [ ]:
descr = df.describe()

In [ ]:
type(descr)

pandas.core.frame.DataFrame

In [ ]:
descr

Calories  Protein (g)        Fat      Sodium  Dietary Fiber  \
count   74.000000    74.000000  74.000000   74.000000      74.000000   
mean   105.540541     2.500000   0.945946  160.675676       2.090541   
std     18.442201     1.088546   0.963610   85.188447       2.404002   
min     50.000000     1.000000   0.000000    0.000000       0.000000   
25%    100.000000     2.000000   0.000000  131.250000       0.250000   
50%    110.000000     2.000000   1.000000  180.000000       1.500000   
75%    110.000000     3.000000   1.000000  217.500000       3.000000   
max    160.000000     6.000000   5.000000  320.000000      14.000000   

           Carbs     Sugars  Display Shelf   Potassium  Vitamins and Minerals  \
count  74.000000  74.000000      74.000000   74.000000              74.000000   
mean   14.594595   6.770270       2.175676   92.675676              28.378378   
std     4.349205   4.467684       0.833512   70.578065              22.787104   
min    -1.000000  -1.000000       1.000000   -1.000000               0.000000   
25%    12.000000   3.000000       1.000000   40.000000              25.000000   
50%    14.000000   6.000000       2.000000   90.000000              25.000000   
75%    17.000000  10.750000       3.000000  113.750000              25.000000   
max    23.000000  15.000000       3.000000  330.000000             100.000000   

       Serving Size Weight  Cups per Serving  
count            74.000000         74.000000  
mean              1.027432          0.629054  
std               0.151260          0.576843  
min               0.500000         -1.000000  
25%               1.000000          0.670000  
50%               1.000000          0.750000  
75%               1.000000          1.000000  
max               1.500000          1.500000

In [ ]:
df[1:4]

Cereal Name Manufacturer Type  Calories  Protein (g)  Fat  \
1          100%_Natural_Bran  Quaker Oats    C       120            3    5   
2                   All-Bran     Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber     Kelloggs    C        50            4    0   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50

In [ ]:
df[['Manufacturer','Sodium']]

Manufacturer  Sodium
0          Nabisco     130
1      Quaker Oats      15
2         Kelloggs     260
3         Kelloggs     140
4   Ralston Purina     200
..             ...     ...
69   General Mills     250
70   General Mills     140
71  Ralston Purina     230
72   General Mills     200
73   General Mills     200

[74 rows x 2 columns]

In [ ]:
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df1 = df[0:5]
df1

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75

In [ ]:
thirdRow = [False, False, True, False, False]
df1[thirdRow]

Cereal Name Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
2    All-Bran     Kelloggs    C        70            4    1     260   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
2            9.0    7.0       5              3        320   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
2                     25                  1.0              0.33

In [ ]:
condition = df1['Calories'] > 70
df1[condition]

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
1  100%_Natural_Bran     Quaker Oats    C       120            3    5      15   
4     Almond_Delight  Ralston Purina    C       110            2    2     200   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
1            2.0    8.0       8              3        135   
4            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
1                      0                  1.0             -1.00  
4                     25                  1.0              0.75

In [ ]:
df1[ (df1['Calories'] > 70) & (df1['Fat'] < 5)]

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
4  Almond_Delight  Ralston Purina    C       110            2    2     200   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
4            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
4                     25                  1.0              0.75

In [ ]:
df1[ (df1['Calories'] > 70) | (df1['Fat'] < 2)]

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75

In [ ]:
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df.loc[71,'Manufacturer']

'Ralston Purina'

In [ ]:
df.loc[[71],['Manufacturer']]

Manufacturer
71  Ralston Purina

In [ ]:
df.loc[56:71,['Manufacturer','Sodium']]

Manufacturer  Sodium
56   General Mills     140
57        Kelloggs       0
58  Ralston Purina     240
59        Kelloggs     290
60         Nabisco       0
61         Nabisco       0
62         Nabisco       0
63        Kelloggs      70
64        Kelloggs     230
65         Nabisco      15
66   General Mills     200
67   General Mills     190
68   General Mills     200
69   General Mills     250
70   General Mills     140
71  Ralston Purina     230

In [ ]:
df.loc[56:71,'Manufacturer':'Sodium']

Manufacturer Type  Calories  Protein (g)  Fat  Sodium
56   General Mills    C       100            3    2     140
57        Kelloggs    C        90            2    0       0
58  Ralston Purina    C       110            1    0     240
59        Kelloggs    C       110            2    0     290
60         Nabisco    C        80            2    0       0
61         Nabisco    C        90            3    0       0
62         Nabisco    C        90            3    0       0
63        Kelloggs    C       110            2    1      70
64        Kelloggs    C       110            6    0     230
65         Nabisco    C        90            2    0      15
66   General Mills    C       110            2    1     200
67   General Mills    C       140            3    1     190
68   General Mills    C       100            3    1     200
69   General Mills    C       110            2    1     250
70   General Mills    C       110            1    1     140
71  Ralston Purina    C       100            3    1     230

In [ ]:
df.loc[[56,71],'Manufacturer':'Sodium']

Manufacturer Type  Calories  Protein (g)  Fat  Sodium
56   General Mills    C       100            3    2     140
71  Ralston Purina    C       100            3    1     230

In [ ]:
 df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df.iloc[9,5]

0

In [ ]:
df.iloc[9,2]

'C'

In [ ]:
df.iloc[[9],[2]]

Type
9    C

In [ ]:
df.iloc[0:5,0:3]

Cereal Name    Manufacturer Type
0                  100%_Bran         Nabisco    C
1          100%_Natural_Bran     Quaker Oats    C
2                   All-Bran        Kelloggs    C
3  All-Bran_with_Extra_Fiber        Kelloggs    C
4             Almond_Delight  Ralston Purina    C

In [ ]:
df.iloc[[0,2,4],0:3]

Cereal Name    Manufacturer Type
0       100%_Bran         Nabisco    C
2        All-Bran        Kelloggs    C
4  Almond_Delight  Ralston Purina    C

In [ ]:
df1

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75

In [ ]:
df1.loc[5] = ['Trix', 'Terepin', 'A', 1200, 10, 500, 300, 10.0, 5.0, 400, 3, 12, 156,1.8, 0.44]

C:\Users\Pc\AppData\Local\Temp\ipykernel_16440\21230520.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[5] = ['Trix', 'Terepin', 'A', 1200, 10, 500, 300, 10.0, 5.0, 400, 3, 12, 156,1.8, 0.44]


In [ ]:
df1

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  \
0                  100%_Bran         Nabisco    C        70            4    1   
1          100%_Natural_Bran     Quaker Oats    C       120            3    5   
2                   All-Bran        Kelloggs    C        70            4    1   
3  All-Bran_with_Extra_Fiber        Kelloggs    C        50            4    0   
4             Almond_Delight  Ralston Purina    C       110            2    2   
5                       Trix         Terepin    A      1200           10  500   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
3     140           14.0    8.0       0              3        330   
4     200            1.0   14.0       8              3         -1   
5     300           10.0    5.0     400              3         12   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
3                     25                  1.0              0.50  
4                     25                  1.0              0.75  
5                    156                  1.8              0.44

In [ ]:
df1.drop(3, axis = 0, inplace=True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_16440\871925474.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(3, axis = 0, inplace=True)


In [ ]:
df1

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
0          100%_Bran         Nabisco    C        70            4    1     130   
1  100%_Natural_Bran     Quaker Oats    C       120            3    5      15   
2           All-Bran        Kelloggs    C        70            4    1     260   
4     Almond_Delight  Ralston Purina    C       110            2    2     200   
5               Trix         Terepin    A      1200           10  500     300   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0           10.0    5.0       6              3        280   
1            2.0    8.0       8              3        135   
2            9.0    7.0       5              3        320   
4            1.0   14.0       8              3         -1   
5           10.0    5.0     400              3         12   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
4                     25                  1.0              0.75  
5                    156                  1.8              0.44

In [ ]:
df1['MyColumn'] = [1, 2, 4, 7, 8]

C:\Users\Pc\AppData\Local\Temp\ipykernel_16440\555354768.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['MyColumn'] = [1, 2, 4, 7, 8]


In [ ]:
df1

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
0          100%_Bran         Nabisco    C        70            4    1     130   
1  100%_Natural_Bran     Quaker Oats    C       120            3    5      15   
2           All-Bran        Kelloggs    C        70            4    1     260   
4     Almond_Delight  Ralston Purina    C       110            2    2     200   
5               Trix         Terepin    A      1200           10  500     300   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0           10.0    5.0       6              3        280   
1            2.0    8.0       8              3        135   
2            9.0    7.0       5              3        320   
4            1.0   14.0       8              3         -1   
5           10.0    5.0     400              3         12   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  MyColumn  
0                     25                  1.0              0.33         1  
1                      0                  1.0             -1.00         2  
2                     25                  1.0              0.33         4  
4                     25                  1.0              0.75         7  
5                    156                  1.8              0.44         8

In [ ]:
df1.drop('MyColumn', axis = 1, inplace = True)

C:\Users\Pc\AppData\Local\Temp\ipykernel_16440\3598458280.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop('MyColumn', axis = 1, inplace = True)


In [ ]:
df

Cereal Name    Manufacturer Type  Calories  Protein (g)  \
0                   100%_Bran         Nabisco    C        70            4   
1           100%_Natural_Bran     Quaker Oats    C       120            3   
2                    All-Bran        Kelloggs    C        70            4   
3   All-Bran_with_Extra_Fiber        Kelloggs    C        50            4   
4              Almond_Delight  Ralston Purina    C       110            2   
..                        ...             ...  ...       ...          ...   
69                    Triples   General Mills    C       110            2   
70                       Trix   General Mills    C       110            1   
71                 Wheat_Chex  Ralston Purina    C       100            3   
72                   Wheaties   General Mills    C       100            3   
73        Wheaties_Honey_Gold   General Mills    C       110            2   

    Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     1     130           10.0    5.0       6              3        280   
1     5      15            2.0    8.0       8              3        135   
2     1     260            9.0    7.0       5              3        320   
3     0     140           14.0    8.0       0              3        330   
4     2     200            1.0   14.0       8              3         -1   
..  ...     ...            ...    ...     ...            ...        ...   
69    1     250            0.0   21.0       3              3         60   
70    1     140            0.0   13.0      12              2         25   
71    1     230            3.0   17.0       3              1        115   
72    1     200            3.0   17.0       3              1        110   
73    1     200            1.0   16.0       8              1         60   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                      25                  1.0              0.33  
1                       0                  1.0             -1.00  
2                      25                  1.0              0.33  
3                      25                  1.0              0.50  
4                      25                  1.0              0.75  
..                    ...                  ...               ...  
69                     25                  1.0              0.75  
70                     25                  1.0              1.00  
71                     25                  1.0              0.67  
72                     25                  1.0              1.00  
73                     25                  1.0              0.75  

[74 rows x 15 columns]

In [ ]:
df.sort_values(by='Calories')

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
3   All-Bran_with_Extra_Fiber       Kelloggs    C        50            4    0   
51                Puffed_Rice    Quaker Oats    C        50            1    0   
52               Puffed_Wheat    Quaker Oats    C        50            2    0   
0                   100%_Bran        Nabisco    C        70            4    1   
2                    All-Bran       Kelloggs    C        70            4    1   
..                        ...            ...  ...       ...          ...  ...   
7                     Basic_4  General Mills    C       130            3    2   
38     Just_Right_Fruit_&_Nut       Kelloggs    C       140            3    1   
46  Nutri-Grain_Almond-Raisin       Kelloggs    C       140            3    2   
67          Total_Raisin_Bran  General Mills    C       140            3    1   
43       Mueslix_Crispy_Blend       Kelloggs    C       160            3    2   

    Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
3      140           14.0    8.0       0              3        330   
51       0            0.0   13.0       0              3         15   
52       0            1.0   10.0       0              3         50   
0      130           10.0    5.0       6              3        280   
2      260            9.0    7.0       5              3        320   
..     ...            ...    ...     ...            ...        ...   
7      210            2.0   18.0       8              3        100   
38     170            2.0   20.0       9              3         95   
46     220            3.0   21.0       7              3        130   
67     190            4.0   15.0      14              3        230   
43     150            3.0   17.0      13              3        160   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
3                      25                 1.00              0.50  
51                      0                 0.50              1.00  
52                      0                 0.50             -1.00  
0                      25                 1.00              0.33  
2                      25                 1.00              0.33  
..                    ...                  ...               ...  
7                      25                 1.33              0.75  
38                    100                 1.30              0.75  
46                     25                 1.33              0.67  
67                    100                 1.50              1.00  
43                     25                 1.50              0.67  

[74 rows x 15 columns]

In [ ]:
df.sort_values(by='Calories', ascending=False)

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
43       Mueslix_Crispy_Blend       Kelloggs    C       160            3    2   
46  Nutri-Grain_Almond-Raisin       Kelloggs    C       140            3    2   
67          Total_Raisin_Bran  General Mills    C       140            3    1   
38     Just_Right_Fruit_&_Nut       Kelloggs    C       140            3    1   
48       Oatmeal_Raisin_Crisp  General Mills    C       130            3    2   
..                        ...            ...  ...       ...          ...  ...   
2                    All-Bran       Kelloggs    C        70            4    1   
0                   100%_Bran        Nabisco    C        70            4    1   
3   All-Bran_with_Extra_Fiber       Kelloggs    C        50            4    0   
51                Puffed_Rice    Quaker Oats    C        50            1    0   
52               Puffed_Wheat    Quaker Oats    C        50            2    0   

    Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
43     150            3.0   17.0      13              3        160   
46     220            3.0   21.0       7              3        130   
67     190            4.0   15.0      14              3        230   
38     170            2.0   20.0       9              3         95   
48     170            1.5   13.5      10              3        120   
..     ...            ...    ...     ...            ...        ...   
2      260            9.0    7.0       5              3        320   
0      130           10.0    5.0       6              3        280   
3      140           14.0    8.0       0              3        330   
51       0            0.0   13.0       0              3         15   
52       0            1.0   10.0       0              3         50   

    Vitamins and Minerals  Serving Size Weight  Cups per Serving  
43                     25                 1.50              0.67  
46                     25                 1.33              0.67  
67                    100                 1.50              1.00  
38                    100                 1.30              0.75  
48                     25                 1.25              0.50  
..                    ...                  ...               ...  
2                      25                 1.00              0.33  
0                      25                 1.00              0.33  
3                      25                 1.00              0.50  
51                      0                 0.50              1.00  
52                      0                 0.50             -1.00  

[74 rows x 15 columns]

In [ ]:
df.sort_values(by='Manufacturer')

Cereal Name                 Manufacturer Type  Calories  \
42                Maypo  American Home Food Products    H       100   
73  Wheaties_Honey_Gold                General Mills    C       110   
56      Raisin_Nut_Bran                General Mills    C       100   
35   Honey_Nut_Cheerios                General Mills    C       110   
72             Wheaties                General Mills    C       100   
..                  ...                          ...  ...       ...   
15            Corn_Chex               Ralston Purina    C       110   
8             Bran_Chex               Ralston Purina    C        90   
4        Almond_Delight               Ralston Purina    C       110   
71           Wheat_Chex               Ralston Purina    C       100   
58            Rice_Chex               Ralston Purina    C       110   

    Protein (g)  Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  \
42            4    1       0            0.0   16.0       3              2   
73            2    1     200            1.0   16.0       8              1   
56            3    2     140            2.5   10.5       8              3   
35            3    1     250            1.5   11.5      10              1   
72            3    1     200            3.0   17.0       3              1   
..          ...  ...     ...            ...    ...     ...            ...   
15            2    0     280            0.0   22.0       3              1   
8             2    1     200            4.0   15.0       6              1   
4             2    2     200            1.0   14.0       8              3   
71            3    1     230            3.0   17.0       3              1   
58            1    0     240            0.0   23.0       2              1   

    Potassium  Vitamins and Minerals  Serving Size Weight  Cups per Serving  
42         95                     25                  1.0             -1.00  
73         60                     25                  1.0              0.75  
56        140                     25                  1.0              0.50  
35         90                     25                  1.0              0.75  
72        110                     25                  1.0              1.00  
..        ...                    ...                  ...               ...  
15         25                     25                  1.0              1.00  
8         125                     25                  1.0              0.67  
4          -1                     25                  1.0              0.75  
71        115                     25                  1.0              0.67  
58         30                     25                  1.0              1.13  

[74 rows x 15 columns]

In [ ]:
df.sort_values(by='Manufacturer', ascending=False)

Cereal Name                 Manufacturer Type  Calories  \
58             Rice_Chex               Ralston Purina    C       110   
71            Wheat_Chex               Ralston Purina    C       100   
4         Almond_Delight               Ralston Purina    C       110   
23           Double_Chex               Ralston Purina    C       100   
8              Bran_Chex               Ralston Purina    C        90   
..                   ...                          ...  ...       ...   
44  Multi-Grain_Cheerios                General Mills    C       100   
35    Honey_Nut_Cheerios                General Mills    C       110   
41          Lucky_Charms                General Mills    C       110   
73   Wheaties_Honey_Gold                General Mills    C       110   
42                 Maypo  American Home Food Products    H       100   

    Protein (g)  Fat  Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  \
58            1    0     240            0.0   23.0       2              1   
71            3    1     230            3.0   17.0       3              1   
4             2    2     200            1.0   14.0       8              3   
23            2    0     190            1.0   18.0       5              3   
8             2    1     200            4.0   15.0       6              1   
..          ...  ...     ...            ...    ...     ...            ...   
44            2    1     220            2.0   15.0       6              1   
35            3    1     250            1.5   11.5      10              1   
41            2    1     180            0.0   12.0      12              2   
73            2    1     200            1.0   16.0       8              1   
42            4    1       0            0.0   16.0       3              2   

    Potassium  Vitamins and Minerals  Serving Size Weight  Cups per Serving  
58         30                     25                  1.0              1.13  
71        115                     25                  1.0              0.67  
4          -1                     25                  1.0              0.75  
23         80                     25                  1.0              0.75  
8         125                     25                  1.0              0.67  
..        ...                    ...                  ...               ...  
44         90                     25                  1.0              1.00  
35         90                     25                  1.0              0.75  
41         55                     25                  1.0              1.00  
73         60                     25                  1.0              0.75  
42         95                     25                  1.0             -1.00  

[74 rows x 15 columns]

In [ ]:
df1.to_csv('datinfamin.csv', index_label=False)

In [ ]:
nuevoDF = pd.read_csv('datinfamin.csv')

In [ ]:
nuevoDF

Cereal Name    Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
0          100%_Bran         Nabisco    C        70            4    1     130   
1  100%_Natural_Bran     Quaker Oats    C       120            3    5      15   
2           All-Bran        Kelloggs    C        70            4    1     260   
4     Almond_Delight  Ralston Purina    C       110            2    2     200   
5               Trix         Terepin    A      1200           10  500     300   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0           10.0    5.0       6              3        280   
1            2.0    8.0       8              3        135   
2            9.0    7.0       5              3        320   
4            1.0   14.0       8              3         -1   
5           10.0    5.0     400              3         12   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33  
4                     25                  1.0              0.75  
5                    156                  1.8              0.44

In [ ]:
df2 = df[0:3]
df3 = df[5:8]

In [ ]:
df2

Cereal Name Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
0          100%_Bran      Nabisco    C        70            4    1     130   
1  100%_Natural_Bran  Quaker Oats    C       120            3    5      15   
2           All-Bran     Kelloggs    C        70            4    1     260   

   Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0           10.0    5.0       6              3        280   
1            2.0    8.0       8              3        135   
2            9.0    7.0       5              3        320   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                  1.0              0.33  
1                      0                  1.0             -1.00  
2                     25                  1.0              0.33

In [ ]:
df3

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
5  Apple_Cinnamon_Cheerios  General Mills    C       110            2    2   
6              Apple_Jacks       Kelloggs    C       110            2    0   
7                  Basic_4  General Mills    C       130            3    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
5     180            1.5   10.5      10              1         70   
6     125            1.0   11.0      14              2         30   
7     210            2.0   18.0       8              3        100   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
5                     25                 1.00              0.75  
6                     25                 1.00              1.00  
7                     25                 1.33              0.75

In [ ]:
df3 = df3.reset_index(drop = True)

In [ ]:
df3

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
0  Apple_Cinnamon_Cheerios  General Mills    C       110            2    2   
1              Apple_Jacks       Kelloggs    C       110            2    0   
2                  Basic_4  General Mills    C       130            3    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     180            1.5   10.5      10              1         70   
1     125            1.0   11.0      14              2         30   
2     210            2.0   18.0       8              3        100   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                 1.00              0.75  
1                     25                 1.00              1.00  
2                     25                 1.33              0.75

In [ ]:
pd.concat([df2,df3], axis=1)

Cereal Name Manufacturer Type  Calories  Protein (g)  Fat  Sodium  \
0          100%_Bran      Nabisco    C        70            4    1     130   
1  100%_Natural_Bran  Quaker Oats    C       120            3    5      15   
2           All-Bran     Kelloggs    C        70            4    1     260   

   Dietary Fiber  Carbs  Sugars  ...  Fat  Sodium  Dietary Fiber  Carbs  \
0           10.0    5.0       6  ...    2     180            1.5   10.5   
1            2.0    8.0       8  ...    0     125            1.0   11.0   
2            9.0    7.0       5  ...    2     210            2.0   18.0   

   Sugars Display Shelf Potassium Vitamins and Minerals  Serving Size Weight  \
0      10             1        70                    25                 1.00   
1      14             2        30                    25                 1.00   
2       8             3       100                    25                 1.33   

   Cups per Serving  
0              0.75  
1              1.00  
2              0.75  

[3 rows x 30 columns]

In [ ]:
 pd.concat([df2,df3])

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
0                100%_Bran        Nabisco    C        70            4    1   
1        100%_Natural_Bran    Quaker Oats    C       120            3    5   
2                 All-Bran       Kelloggs    C        70            4    1   
0  Apple_Cinnamon_Cheerios  General Mills    C       110            2    2   
1              Apple_Jacks       Kelloggs    C       110            2    0   
2                  Basic_4  General Mills    C       130            3    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
0     180            1.5   10.5      10              1         70   
1     125            1.0   11.0      14              2         30   
2     210            2.0   18.0       8              3        100   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                 1.00              0.33  
1                      0                 1.00             -1.00  
2                     25                 1.00              0.33  
0                     25                 1.00              0.75  
1                     25                 1.00              1.00  
2                     25                 1.33              0.75

In [ ]:
 pd.concat([df2,df3], axis=0)

Cereal Name   Manufacturer Type  Calories  Protein (g)  Fat  \
0                100%_Bran        Nabisco    C        70            4    1   
1        100%_Natural_Bran    Quaker Oats    C       120            3    5   
2                 All-Bran       Kelloggs    C        70            4    1   
0  Apple_Cinnamon_Cheerios  General Mills    C       110            2    2   
1              Apple_Jacks       Kelloggs    C       110            2    0   
2                  Basic_4  General Mills    C       130            3    2   

   Sodium  Dietary Fiber  Carbs  Sugars  Display Shelf  Potassium  \
0     130           10.0    5.0       6              3        280   
1      15            2.0    8.0       8              3        135   
2     260            9.0    7.0       5              3        320   
0     180            1.5   10.5      10              1         70   
1     125            1.0   11.0      14              2         30   
2     210            2.0   18.0       8              3        100   

   Vitamins and Minerals  Serving Size Weight  Cups per Serving  
0                     25                 1.00              0.33  
1                      0                 1.00             -1.00  
2                     25                 1.00              0.33  
0                     25                 1.00              0.75  
1                     25                 1.00              1.00  
2                     25                 1.33              0.75

In [ ]:
 rarin = pd.concat([df2,df3], axis=0)

In [ ]:
rarin[0]

KeyError: 0

In [ ]:
data = {'Gender':['female', 'male', 'female','male'], 'Score':[85,88,95,80]}
df = pd.DataFrame.from_dict(data)
df

In [ ]:
df.groupby(df['Gender']).mean()

KeyError: 'Gender'

In [ ]:
df.groupby(df['Gender']).sum()

KeyError: 'Gender'


---


Estas notebooks corresponden a la asignatura electiva para la Licenciatura en Matemática del Departamento de Matemática de la Escuela de Cs. Exactas y Naturales, de la Facultad de Cs. Exactas, Ingenieria y Agrimensura (FCEIA) de la Universidad Nacional de Rosario, Argentina. Año 2023.

Fueron confeccionadas a tal fin por las docentes investigadoras de la FCEIA Isolda Cardoso y Jorgelina Walpen. Este trabajo de análisis, estudio, recopilación, traducción, armado, pruebas y errores, nos ha llevado mucho tiempo. Cuando hay tanta información disponible es complicado extraer lo que, al menos para nosotras, es relevante. Hay muchísimos otros recursos y tutoriales, nosotras armamos este.

Si estas notebooks son reproducidas, solicitamos citar la fuente.

Dejamos nuestras páginas laborales y repositorios de GitHub. Seguramente en un futuro las pondremos a disposición en el Repositorio Hipermedial de la UNR.

Isolda: Te dejo mi página laboral https://www.fceia.unr.edu.ar/~isolda/ y mi GitHub https://github.com/IsoldaEugenia. Sentite libre de contactarme.

Jorgelina: https://www.fceia.unr.edu.ar/~walpen/ y  https://github.com/JorWalpen